# GitHub Sponsors 후원 설정
# 이 파일은 저장소의 "Sponsor" 버튼을 활성화합니다.
# 자세한 내용: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# GitHub Sponsors 사용자명
github: [krdn]

# Patreon 사용자명
# patreon: username

# Open Collective 사용자명
# open_collective: username

# Ko-fi 사용자명
# ko_fi: username

# Tidelift 패키지명 (platform-name/package-name)
# tidelift: npm/package-name

# Buy Me a Coffee 사용자명
# buy_me_a_coffee: username

# Liberapay 사용자명
# liberapay: username

# IssueHunt 사용자명
# issuehunt: username

# Otechie 사용자명
# otechie: username

# LFX Crowdfunding 프로젝트명
# lfx_crowdfunding: project-name

# 커스텀 후원 링크 (최대 4개)
# custom: ["https://www.paypal.me/username", "https://example.com/donate"]
