name: ✨ 기능 요청
description: 새로운 기능이나 개선 사항을 제안합니다
title: "[Feature]: "
labels: ["type: enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        새로운 아이디어를 공유해 주셔서 감사합니다!
        Claude Code 워크플로를 개선할 수 있는 제안을 환영합니다.

  - type: dropdown
    id: category
    attributes:
      label: 카테고리
      description: 제안하는 기능의 카테고리를 선택해 주세요
      options:
        - 새 문서 추가
        - 새 워크플로 패턴
        - 새 예제 추가
        - 새 템플릿 추가
        - 기존 콘텐츠 개선
        - 기타
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: 관련 영역
      description: 관련된 영역을 선택해 주세요 (해당되는 경우)
      options:
        - Hooks
        - MCP 서버
        - Prompts
        - 코드 리뷰
        - 디버깅
        - 리팩토링
        - 해당 없음
    validations:
      required: false

  - type: textarea
    id: problem
    attributes:
      label: 해결하고자 하는 문제
      description: 이 기능이 해결할 문제나 필요성을 설명해 주세요
      placeholder: "예: Claude Code로 테스트를 작성할 때 가이드가 부족합니다..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 제안하는 해결책
      description: 어떤 기능이나 콘텐츠가 추가되면 좋을지 설명해 주세요
      placeholder: 원하는 기능에 대한 명확하고 간결한 설명
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 고려한 대안
      description: 다른 대안을 고려해 보셨다면 설명해 주세요
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: 추가 정보
      description: 참고 자료나 예시가 있다면 첨부해 주세요
    validations:
      required: false
