name: ❓ 질문
description: Claude Code 사용에 관한 질문을 합니다
title: "[Question]: "
labels: ["type: question"]
body:
  - type: markdown
    attributes:
      value: |
        질문해 주셔서 감사합니다!
        Claude Code 사용에 관한 질문을 환영합니다.

        **참고**: 먼저 [기존 문서](https://github.com/krdn/claude-code-workflow/tree/main/docs)를 확인해 주세요.

  - type: dropdown
    id: category
    attributes:
      label: 질문 카테고리
      description: 질문의 카테고리를 선택해 주세요
      options:
        - 시작하기 / 설정
        - 워크플로 패턴
        - Hooks 사용
        - MCP 서버
        - 프롬프트 작성
        - CLAUDE.md 설정
        - 기타
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: 질문 내용
      description: 질문을 자세히 작성해 주세요
      placeholder: 궁금한 점을 설명해 주세요
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: 컨텍스트
      description: 질문의 배경이나 시도해본 것이 있다면 설명해 주세요
      placeholder: |
        - 어떤 상황에서 이 문제가 발생했나요?
        - 이미 시도해본 방법이 있나요?
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: 환경 정보 (선택)
      description: 관련된 경우 환경 정보를 작성해 주세요
      placeholder: |
        - OS:
        - Claude Code 버전:
        - IDE:
    validations:
      required: false
